[package]
name = "dia09_calcetines_magicos"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]  # Importante para contratos Soroban

[dependencies]
soroban-sdk = {  version = "23", features = ["testutils"] }  
